"""Phase 203 replay tests for v1.43 OBSV-06 / OBSV-07 aggregator side.

Dual-fixture strategy:
  * synthetic NDJSON fixture plus checked-in golden summary JSON. Aggregator
    output must byte-equal golden after canonical JSON serialization.
  * v1.42 reference soak NDJSON regression proves the inline-jq → Python
    promotion preserves diagnostic_distribution math on unaffected fields.

The synthetic fixture is generated by tests/fixtures/_phase_203_generator.py; a
drift-detection test re-runs the generator and asserts byte-identical output
against the checked-in fixture.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
AGGREGATOR_PATH = REPO_ROOT / "scripts" / "soak_summary_aggregate.py"
SYNTHETIC_NDJSON = REPO_ROOT / "tests" / "fixtures" / "phase_203_synthetic_capture.ndjson"
SYNTHETIC_SUMMARY = REPO_ROOT / "tests" / "fixtures" / "phase_203_synthetic_summary.json"
V142_NDJSON = (
    REPO_ROOT
    / ".planning"
    / "milestones"
    / "v1.42-phases"
    / "201-docsis-aware-ul-congestion-control"
    / "soak"
    / "20260505T132736Z"
    / "soak-capture.ndjson"
)
V142_SUMMARY = V142_NDJSON.with_name("soak-summary.json")


def _load_module(path: Path, name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def aggregator() -> ModuleType:
    return _load_module(AGGREGATOR_PATH, "soak_aggregator")


class TestAggregatorMath:
    """OBSV-06 + OBSV-07: synthetic NDJSON → exact golden match."""

    def test_aggregate_soak_matches_golden(self, aggregator: ModuleType) -> None:
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        golden = json.loads(SYNTHETIC_SUMMARY.read_text(encoding="utf-8"))
        assert json.dumps(result, sort_keys=True, indent=2) == json.dumps(
            golden, sort_keys=True, indent=2
        ), (
            "Aggregator output drifted from golden summary. If intentional, "
            "regenerate tests/fixtures/phase_203_synthetic_summary.json."
        )

    def test_all_twelve_cells_populated(self, aggregator: ModuleType) -> None:
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        for zone in ("GREEN", "YELLOW", "SOFT_RED", "RED"):
            for cause in ("dwell_hold", "backlog_recovery", "other"):
                cell = result["load_rtt_delta_us_by_zone_cause"][zone][cause]
                assert cell["count"] >= 3, f"({zone}, {cause}) undercount"

    def test_histogram_contains_overflow_bin(self, aggregator: ModuleType) -> None:
        """The 350000 µs row in ROW_CATALOG lands in the overflow cell."""
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        top_hist = result["diagnostic_distribution"]["load_rtt_delta_us"]["histogram"]
        assert len(top_hist["counts"]) == len(top_hist["buckets_us"]) + 1
        assert top_hist["counts"][-1] >= 1

    def test_samples_filtered_null_counted(self, aggregator: ModuleType) -> None:
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        top = result["diagnostic_distribution"]["load_rtt_delta_us"]
        assert top["samples_filtered_null"] == 3


class TestV142NdjsonRegression:
    """Backward-compat: v1.42 diagnostic_distribution math preserved."""

    def test_v142_diagnostic_distribution_matches_inline_jq(self, aggregator: ModuleType) -> None:
        if not V142_NDJSON.exists() or not V142_SUMMARY.exists():
            pytest.skip(f"v1.42 reference fixtures absent at {V142_NDJSON}")
        result = aggregator.aggregate_soak(V142_NDJSON)
        v142 = json.loads(V142_SUMMARY.read_text(encoding="utf-8"))
        v142_diag = v142["diagnostic_distribution"]
        ours = result["diagnostic_distribution"]
        assert ours["rtt_integral_ms_s"]["mean"] == pytest.approx(
            v142_diag["rtt_integral_ms_s"]["mean"], rel=0.01
        )
        assert ours["rtt_integral_ms_s"]["max"] == pytest.approx(
            v142_diag["rtt_integral_ms_s"]["max"], rel=0.01
        )
        assert ours["max_delay_delta_us"]["mean"] == pytest.approx(
            v142_diag["max_delay_delta_us"]["mean"], rel=0.01
        )
        assert ours["max_delay_delta_us"]["max"] == v142_diag["max_delay_delta_us"]["max"]
        assert ours["red_streak"]["max"] == v142_diag["red_streak"]["max"]
        assert ours["headroom_exhausted_samples"] == v142_diag["headroom_exhausted_samples"]
        assert ours["total_samples"] == v142_diag["total_samples"]

    def test_v142_load_rtt_delta_emits_zero_cells(self, aggregator: ModuleType) -> None:
        if not V142_NDJSON.exists():
            pytest.skip(f"v1.42 reference fixture absent at {V142_NDJSON}")
        result = aggregator.aggregate_soak(V142_NDJSON)
        top = result["diagnostic_distribution"]["load_rtt_delta_us"]
        assert top["count"] == 0
        assert top["max"] == 0
        for zone in ("GREEN", "YELLOW", "SOFT_RED", "RED"):
            for cause in ("dwell_hold", "backlog_recovery", "other"):
                cell = result["load_rtt_delta_us_by_zone_cause"][zone][cause]
                assert cell["count"] == 0, f"({zone},{cause}) should be empty"


class TestGeneratorDriftDetection:
    """Re-running the generator must produce byte-identical NDJSON."""

    def test_fixture_matches_generator_output(self) -> None:
        generator_path = REPO_ROOT / "tests" / "fixtures" / "_phase_203_generator.py"
        generator = _load_module(generator_path, "phase_203_generator")
        regenerated = generator.generate_synthetic_ndjson()
        checked_in = SYNTHETIC_NDJSON.read_text(encoding="utf-8")
        assert regenerated == checked_in, (
            "Generator output drifted from checked-in fixture. Re-run "
            "python tests/fixtures/_phase_203_generator.py and regenerate the "
            "golden summary if intentional."
        )


class TestZoneAxisUploadOnly:
    """The aggregator reads last_zone (upload-side) only."""

    def test_zone_axis_metadata(self, aggregator: ModuleType) -> None:
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        assert result["phase_203_metadata"]["zone_axis"] == "upload"

    def test_only_four_upload_zones_in_matrix(self, aggregator: ModuleType) -> None:
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        assert set(result["load_rtt_delta_us_by_zone_cause"]) == {
            "GREEN",
            "YELLOW",
            "SOFT_RED",
            "RED",
        }


class TestCauseAttribution:
    """Dual-attribution + first-row exclusion per locked decisions."""

    def test_dual_attribution_documented_in_metadata(self, aggregator: ModuleType) -> None:
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        assert result["phase_203_metadata"]["attribution_policy"] == "dual"

    def test_multi_cause_row_dual_attributed(self, aggregator: ModuleType) -> None:
        """The MULTI row increments dwell_hold and backlog_recovery."""
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        yellow = result["load_rtt_delta_us_by_zone_cause"]["YELLOW"]
        assert yellow["dwell_hold"]["count"] == 4
        assert yellow["backlog_recovery"]["count"] == 4

    def test_first_row_excluded_from_matrix(self, aggregator: ModuleType) -> None:
        """Row 0 has no previous sample and must not enter any matrix cell."""
        result = aggregator.aggregate_soak(SYNTHETIC_NDJSON)
        top_total = result["diagnostic_distribution"]["load_rtt_delta_us"]["samples_total"]
        assert top_total >= 1
        green = result["load_rtt_delta_us_by_zone_cause"]["GREEN"]
        assert green["dwell_hold"]["count"] == 4, (
            "GREEN dwell_hold count should be rows 1-4 only; row 0's 142 µs "
            "delta must be excluded from cause attribution."
        )
